Commit changes from https://github.com/tnierman/old-backplane-tools
openshift/backplane-tools pull request #1
Opened 2023-04-19 17:57 UTC by tnierman

Adds changes from [prototyping repo](https://github.com/tnierman/old-backplane-tools) to the official backplane-tools repo

2023-04-24 12:47 UTC, NautiluX requested changes

2023-04-24 12:47 UTC, NautiluX commented on pkg/tool/ocm/ocm.go
> +assetLoop:
do we need this label if there is no nested loop?

2023-04-24 12:47 UTC, NautiluX commented on pkg/tool/ocm/ocm.go
> +			continue assetLoop
```suggestion
			continue
```

2023-04-24 12:47 UTC, NautiluX commented on pkg/tool/ocm/ocm.go
> +			continue assetLoop
```suggestion
			continue
```

2023-04-24 12:47 UTC, NautiluX commented on pkg/tool/ocm/ocm.go
> +		}
```suggestion
			}
			checksumAsset = asset
			continue
		}
		if ocmBinaryAsset.GetName() != "" {
			return fmt.Errorf("detected duplicate ocm-cli binary assets")
		}
		ocmBinaryAsset = asset
		}
```

2023-04-24 17:43 UTC, tnierman commented on pkg/tool/ocm/ocm.go
> +assetLoop:
I prefer to be extremely specific when using `continue`, but admittedly there's probably no need here.

2023-04-28 13:39 UTC, mjlshen commented
/retest

2023-05-02 00:14 UTC, mjlshen commented
/retest

2023-05-03 00:23 UTC, tnierman commented
/retest

2023-05-03 00:23 UTC, mjlshen commented
/retest

2023-05-03 00:25 UTC, tnierman commented
/lgtm

2023-05-03 00:36 UTC, mjlshen reviewed
/lgtm

2023-05-03 00:39 UTC, merged

2023-05-03 00:44 UTC, tnierman commented
/honk

2023-05-03 00:50 UTC, karthikperu7 commented
/pony

2023-05-03 00:52 UTC, karthikperu7 commented
/joke