Add go install instructions
openshift/backplane-tools pull request #22
Opened 2023-11-13 08:01 UTC by NautiluX

2023-11-13 11:00 UTC, typeid requested changes

2023-11-13 11:00 UTC, typeid commented on README.md
> +go install github.com/openshift/backplane-tools; backplane-tools install all
```suggestion
go install github.com/openshift/backplane-tools@latest; backplane-tools install all
```

Otherwise it errors with the following: 
```
go install github.com/openshift/backplane-tools; backplane-tools install all
go: 'go install' requires a version when current directory is not in a module
	Try 'go install github.com/openshift/backplane-tools@latest' to install the latest version
bash: backplane-tools: command not found...
```

2023-11-17 09:12 UTC, T0MASD commented
The following  is used for building backplane tools in ocm-container:

https://github.com/openshift/ocm-container/blob/master/Dockerfile#L211-L231

Could it be re-used here? Perhaps with some kind of `curl https://github.com/openshift/backplane-tools/install.sh`

2023-12-07 15:17 UTC, typeid commented
/lgtm

2023-12-07 15:22 UTC, merged